name: gase
channels:
  - conda-forge
dependencies:
  - gdal=3.4.3
  - pip
  - pip:
      - geopandas
      - pillow
      - opencv
      - numpy
      - keplergl
      - streamlit
      - localtileserver
      - palettable
      - streamlit-folium
      - streamlit-keplergl
      - streamlit-bokeh-events
      - git+https://github.com/giswqs/leafmap
      - git+https://github.com/giswqs/geemap
